run:
  timeout: 5m
  tests: true
  modules-download-mode: readonly

linters:
  enable:
    - errcheck       # Check for unchecked errors
    - gosimple       # Simplify code
    - govet          # Vet examines Go source code and reports suspicious constructs
    - ineffassign    # Detects ineffectual assignments
    - staticcheck    # Advanced Go linter
    - typecheck      # Type checks Go code
    - unused         # Checks for unused constants, variables, functions and types
    - gofmt          # Checks whether code was gofmt-ed
    - goimports      # Check import statements are formatted according to the 'goimport' command
    - misspell       # Finds commonly misspelled English words in comments
    - revive         # Fast, configurable, extensible, flexible, and beautiful linter for Go
    - godox          # Detects FIXME, TODO and other comment keywords
    - gocritic       # Provides diagnostics that check for bugs, performance and style issues
    - gocyclo        # Computes and checks the cyclomatic complexity of functions
    - gosec          # Inspects source code for security problems
    - unconvert      # Remove unnecessary type conversions
    - unparam        # Reports unused function parameters

linters-settings:
  errcheck:
    check-type-assertions: true
    check-blank: true

  govet:
    enable-all: true
    disable:
      - shadow

  goimports:
    local-prefixes: github.com/tung-dnt/nestjs-serverless-workflow

  revive:
    confidence: 0.8
    rules:
      - name: blank-imports
      - name: context-as-argument
      - name: context-keys-type
      - name: dot-imports
      - name: error-return
      - name: error-strings
      - name: error-naming
      - name: exported
      - name: if-return
      - name: increment-decrement
      - name: var-naming
      - name: var-declaration
      - name: package-comments
      - name: range
      - name: receiver-naming
      - name: time-naming
      - name: unexported-return
      - name: indent-error-flow
      - name: errorf
      - name: empty-block
      - name: superfluous-else
      - name: unused-parameter
      - name: unreachable-code
      - name: redefines-builtin-id

  gocyclo:
    min-complexity: 15

  gosec:
    excludes:
      - G204 # Audit use of command execution

  gocritic:
    enabled-tags:
      - diagnostic
      - style
      - performance
    disabled-checks:
      - unnamedResult
      - hugeParam

issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0

  exclude-rules:
    # Exclude some linters from running on tests files
    - path: _test\.go
      linters:
        - gocyclo
        - errcheck
        - gosec
        - gocritic

output:
  format: colored-line-number
  print-issued-lines: true
  print-linter-name: true
